name: "Build Package Workflow"
env:
  DOCKER_COMPOSE_VERSION: 1.23.0

on:
  push:
    branches:
      - develop
      - release-*

jobs:
  BUILD_PACKAGE:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    permissions:
      contents: read
      packages: write
    env:
        BUILD_PACKAGE: true
        ARCH: ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.4
        id: go
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 20.10
          docker_channel: stable
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          path: src/github.com/goharbor/harbor
      - name: Build Base Image
        if: |
            github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release-*'
        run: |
          set -x
          cd make/photon/common
          docker build -t ghcr.io/${{ github.repository_owner }}/photon:5.0 .
          docker push ghcr.io/${{ github.repository_owner }}/photon:5.0
          echo "BUILD_BASE=true" >> $GITHUB_ENV
        env:
          GHCR_USERNAME: ${{ github.repository_owner }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Package
        env:
          GHCR_USERNAME: ${{ github.repository_owner }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          env
          df -h
          target_branch="$(echo ${GITHUB_REF#refs/heads/})"
          harbor_offline_build_bundle=""
          harbor_online_build_bundle=""
          # the target release version is the version of next release(RC or GA). It needs to be updated on creating new release branch.
          target_release_version=$(cat ./VERSION)
          Harbor_Package_Version=$target_release_version-'build.'$GITHUB_RUN_NUMBER

          if [[ $target_branch == "develop" ]]; then
            Harbor_Assets_Version=$Harbor_Package_Version
          else
            Harbor_Assets_Version=$target_release_version
          fi

          if [[ $target_branch == "release-"* ]]; then
            Harbor_Build_Base_Tag=$target_release_version
          else
            Harbor_Build_Base_Tag=dev
          fi

          cd src/github.com/goharbor/harbor

          # Build with GHCR namespace for final images, but pull base images from Docker Hub
          sudo make build \
            IMAGENAMESPACE=ghcr.io/${{ github.repository_owner }} \
            BASEIMAGENAMESPACE=goharbor \
            REGISTRYUSER="${{ github.actor }}" \
            REGISTRYPASSWORD="${{ secrets.GITHUB_TOKEN }}" \
            PULL_BASE_FROM_DOCKERHUB=true \
            PUSHBASEIMAGE=false \
            BUILD_BASE=false \
            NPM_REGISTRY=https://registry.npmjs.org \
            VERSIONTAG=${Harbor_Assets_Version} \
            BASEIMAGETAG=${Harbor_Build_Base_Tag}

          # Tag images with arch suffix
          for img in $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'ghcr.io/${{ github.repository_owner }}/harbor-' | grep -v '\-base'); do
            arch_suffix=""
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              arch_suffix="-arm64"
            else
              arch_suffix="-amd64"
            fi
            docker tag "$img" "${img}${arch_suffix}"
            docker push "${img}${arch_suffix}"
          done